controller:
  kind: DaemonSet

  ingressClassResource:
    default: true

  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443

  metrics:
    enabled: false
    serviceMonitor:
      enabled: false

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
